spring:
  datasource:
    username: oggima
    url: jdbc:sqlserver://localhost;databaseName=oggima
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    password: chQjLyKz%!Uj
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      ddl-auto: create-drop
    show-sql: 'true'
